#!/bin/bash

# requieres dunst hyprpicker imagemagick wl-clipboard

TEMP_DIR=/tmp/colorpicker
HEX_COLOR=$(hyprpicker)

mkdir -p $TEMP_DIR

HEX="${HEX_COLOR#\#}"
FNAME="$TEMP_DIR/$HEX.png"

convert -size 100x100 xc:"$HEX_COLOR" "$FNAME"

COLOR_CODE="$HEX_COLOR"

echo "$COLOR_CODE" | wl-copy -n

dunstify -u low -a "Color Picker" -i "$FNAME" $COLOR_CODE "Copied to clipboard"
