#!/bin/bash

Icon="$HOME/.config/hypr/scripts/assets/update.svg"

while true; do
    updates_arch=$(checkupdates | wc -l)
    updates_aur=$(yay -Qua | wc -l)
    updates=$((updates_arch + updates_aur))

    if [[ $updates > 0 ]]; then
        if [[ $updates_arch = 0 && $updates_aur > 0 ]]; then
            notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$Icon" -a "Updates" "Update(s) Available" "$updates Aur Package(s) available for update"
        elif [[ $updates_aur = 0 && $updates_arch > 0 ]]; then
            notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$Icon" -a "Updates" "Update(s) Available" "$updates Pacman Package(s) available for update"
        elif [[ $updates_aur > 0 && $updates_arch > 0 ]]; then
            notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$Icon" -a "Updates" "Update(s) Available" "$updates_arch Pacman and $updates_aur Aur Package(s) available for update"
        elif [[ $updates = 0 ]]; then
            echo $updates
        fi
    fi
    sleep 3h
done
