format = """
[](#3B4252)\
$username\
[](bg:#434C5E fg:#3B4252)\
$directory\
[](fg:#434C5E bg:#4C566A)\
$git_branch\
$git_status\
[](fg:#4C566A bg:#4d4672)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$lua\
$nodejs\
$perl\
$php\
$python\
$rlang\
$ruby\
$rust\
[](fg:#4d4672 bg:#4F367A)\
$docker_context\
$kubernetes\
$nix_shell\
[](fg:#4F367A bg:#694AA1)\
$time\
[](fg:#694AA1)\
"""
command_timeout = 5000

[username]
show_always = true
style_user = "bg:#3B4252"
style_root = "bg:#3B4252"
format = '[$user ]($style)'


[directory]
style = "bg:#434C5E"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "


[git_branch]
symbol = " "
style = "bg:#4C566A"
format = '[ $symbol ($branch)]($style)'

[git_status]
style = "bg:#4C566A"
format = '[$all_status$ahead_behind ]($style)'


[c]
symbol = ""
style = "bg:#4d4672"
format = '[ [$symbol](bg:#4d4672 fg:#6496CE) ($version) ]($style)'

[elixir]
symbol = ""
style = "bg:#4d4672"
format = '[ [$symbol](bg:#4d4672 fg:#A08EAE) ($version) ]($style)'

[elm]
symbol = ""
style = "bg:#4d4672"
format = '[ [$symbol](bg:#4d4672 fg:#2190D2) ($version) ]($style)'

[golang]
symbol = ""
style = "bg:#4d4672"
format = '[ [$symbol](bg:#4d4672 fg:#68D3DF) ($version) ]($style)'

[haskell]
symbol = ""
style = "bg:#4d4672"
format = '[ [$symbol](bg:#4d4672 fg:#D47BEB) ($version) ]($style)'

[java]
symbol = ""
style = "bg:#4d4672"
format = '[ [$symbol](bg:#4d4672 fg:#E06B00) ($version) ]($style)'

[julia]
symbol = ""
style = "bg:#4d4672"
format = '[ [$symbol](bg:#4d4672 fg:#389826) ($version) ]($style)'

[lua]
symbol = ""
style = "bg:#4d4672"
format = '[ [$symbol](bg:#4d4672 fg:#01007F) ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#4d4672"
format = '[ [$symbol](bg:#4d4672 fg:#60B248) ($version) ]($style)'

[perl]
symbol = ""
style = "bg:#4d4672"
format = '[ [$symbol](bg:#4d4672 fg:#0192BB) ($version) ]($style)'

[php]
symbol = ""
style = "bg:#4d4672"
format = '[ [$symbol](bg:#4d4672 fg:#8790BA) ($version) ]($style)'

[python]
symbol = ""
style = "bg:#4d4672"
format = '[ [$symbol](bg:#4d4672 fg:#F9CB3E) ($version) ]($style)'

[rlang]
symbol = ""
style = "bg:#4d4672"
format = '[ [$symbol](bg:#4d4672 fg:#2265B8) ($version) ]($style)'

[ruby]
symbol = ""
style = "bg:#4d4672"
format = '[ [$symbol](bg:#4d4672 fg:#F3645C) ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#4d4672"
format = '[ [$symbol](bg:#4d4672 fg:#EE7C00) ($version) ]($style)'


[docker_context]
symbol = ""
style = "bg:#4F367A"
format = '[ $symbol $context ]($style) $path'

[kubernetes]
symbol = "󱃾"
style = "bg:#4F367A"
format = '[ [$symbol](bg:#4F367A fg:#3B9AD4) ($context) ]($style)'

[nix_shell]
symbol = "󱄅"
style = "bg:#4F367A"
format = '[ [$symbol](bg:#4F367A fg:#80BAE0) $state ]($style)'


[time]
disabled = false
time_format = "%I:%M" # Hour:Minute Format
style = "bg:#694AA1"
format = '[ $time ]($style)'
